### ISSUE TITLE
Review API Docs

### ISSUE THREAD

**Issue by joshhejka** [jhubaseball-io/walkup#4]
The rough [API docs](https://github.com/jhubaseball-io/walkup/wiki/API-Documentation) are now published on the wiki. @dglass7 we can call each other and go over them at some point, or you can just review them and comment here to let me know what you think.

I have a few concerns that I'd like the input of others on:

- Should the modification and retrieval of the team roster happen at their own endpoints (i.e. at `GET/PATCH Team Roster`) or be built in to the team info endpoints (i.e. at `GET/PATCH Team Info`, which also handles `team_description` and Manager info)?
    - The docs currently have this built into `GET/PATCH Team Info`
    - Ideally, I think they'd be separated, but when loading the team page, I don't want the front end to have to call `GET Team Info` and then call `GET Team Roster`; just one API call would be quicker obviously
    - If we do keep them combined, then we'll have to be super clear about what information the backend is expecting from that endpoint at any given time
- What should the API URLs of `GET Account Type` and `GET Team Info` be?
    - Right now, `GET Account Type` is hosted at `[host]/account/{{team_code}}/{{user_code}}/` while `GET Team Info` is hosted at `[host]/team/{{team_code}}/{{user_code}}/`
    - I originally had `GET Account Type` at `[host]/team/{{team_code}}/{{user_code}}/` but I think it's important to include the `user_code` with `GET Team Info` so we can ensure it is the Manager
    - For v2 or v3 of the API, I think we should try to switch to some sort of cookie authorization that will make all of this cleaner
- `PATCH Song Review` has a few things
    - The URL is currently `[host]/song/{{team_code}}/{{user_code}}/{{reviewer_code}}/`, where `reviewer_code` has to be the Manager's `user_code` (gross)
    - The request body currently looks like this (gross):
    ``` js
    {
        "pitcher_submission": {
            "approved": bool,
            "comments": string
        },
        "hitter_submission": {
            "approved": bool,
            "comments": string
        }
    }
   ```
    - Any thoughts on whether these are fine, or ways to improve them? 

Lmk if anybody has thoughts on any of these things, or anything else with the docs.

**Comment by joshhejka** [comment]
Maybe some sort of authorization could be included and when a user first enters their `user_code`, their browser gets a cookie with a token in it and that token could be passed for all future requests? And then `GET Player Info` could be just `[host]/player/{{team_code}}/` and the Player info that is returned would be the one associated with the given request header.

Or is the `user_code` supposed to be complex enough where the authorization isn't really needed? For the ugly `PATCH Song Review` endpoint, could the URL just take the Manager's `user_code` and then the Player's `user_code` is passed in the JSON? Or vice versa? Lmk your thoughts on all of this @dglass7

**Comment by Meber5** [comment]
Personally, I think if we just come up with an 8 digit hexadecimal code and tell the user not to share that with anyone in the email then that should be fine.

**Comment by dglass7** [comment]
Team roster modification should not be its own endpoint. It should be built into GET/PATCH Team Info.

I’m confused about the second one (API URLs for GET Account Type) because it seems like you have `user_code` with GET Team Info in both scenarios. Regardless, there’s nothing wrong with the URLs you have in the first bullet.

Not sure why you think the PATCH Somg Review URL/body are gross. They’re exactly what I would’ve thought and I’m not sure there’s a way to make it prettier

**Comment by joshhejka** [comment]
@dglass7 Yeah my original comment wasn't very clear. I think those endpoint URLs are fine though, one has `team` in the URL and one has `account` but it's not a big deal. And yeah, the `PATCH Song Review` stuff is fine, it's just not as clean as I'd ideally like it to be but it's the best way I could think of.

@Meber5 I would tend to agree at least for this first iteration.

Thanks for the input guys.
